// SvgToXaml
// Copyright (C) 2022-2024 Dust in the Wind
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace DustInTheWind.SvgToXaml.SvgModel;

internal static class SvgNamedColors
{
    public static SvgColor AliceBlue { get; } = new(240, 248, 255);
    public static SvgColor AntiqueWhite { get; } = new(250, 235, 215);
    public static SvgColor Aqua { get; } = new(0, 255, 255);
    public static SvgColor Aquamarine { get; } = new(127, 255, 212);
    public static SvgColor Azure { get; } = new(240, 255, 255);
    public static SvgColor Beige { get; } = new(245, 245, 220);
    public static SvgColor Bisque { get; } = new(255, 228, 196);
    public static SvgColor Black { get; } = new(0, 0, 0);
    public static SvgColor BlanchedAlmond { get; } = new(255, 235, 205);
    public static SvgColor Blue { get; } = new(0, 0, 255);
    public static SvgColor BlueViolet { get; } = new(138, 43, 226);
    public static SvgColor Brown { get; } = new(165, 42, 42);
    public static SvgColor BurlyWood { get; } = new(222, 184, 135);
    public static SvgColor CadetBlue { get; } = new(95, 158, 160);
    public static SvgColor Chartreuse { get; } = new(127, 255, 0);
    public static SvgColor Chocolate { get; } = new(210, 105, 30);
    public static SvgColor Coral { get; } = new(255, 127, 80);
    public static SvgColor CornFlowerBlue { get; } = new(100, 149, 237);
    public static SvgColor CornSilk { get; } = new(255, 248, 220);
    public static SvgColor Crimson { get; } = new(220, 20, 60);
    public static SvgColor Cyan { get; } = new(0, 255, 255);
    public static SvgColor DarkBlue { get; } = new(0, 0, 139);
    public static SvgColor DarkCyan { get; } = new(0, 139, 139);
    public static SvgColor DarkGoldenRod { get; } = new(184, 134, 11);
    public static SvgColor DarkGray { get; } = new(169, 169, 169);
    public static SvgColor DarkGreen { get; } = new(0, 100, 0);
    public static SvgColor DarkGrey { get; } = new(169, 169, 169);
    public static SvgColor DarkKhaki { get; } = new(189, 183, 107);
    public static SvgColor DarkMagenta { get; } = new(139, 0, 139);
    public static SvgColor DarkOliveGreen { get; } = new(85, 107, 47);
    public static SvgColor DarkOrange { get; } = new(255, 140, 0);
    public static SvgColor DarkOrchid { get; } = new(153, 50, 204);
    public static SvgColor DarkRed { get; } = new(139, 0, 0);
    public static SvgColor DarkSalmon { get; } = new(233, 150, 122);
    public static SvgColor DarkSeaGreen { get; } = new(143, 188, 143);
    public static SvgColor DarkSlateBlue { get; } = new(72, 61, 139);
    public static SvgColor DarkSlateGray { get; } = new(47, 79, 79);
    public static SvgColor DarkSlateGrey { get; } = new(47, 79, 79);
    public static SvgColor DarkTurquoise { get; } = new(0, 206, 209);
    public static SvgColor DarkViolet { get; } = new(148, 0, 211);
    public static SvgColor DeepPink { get; } = new(255, 20, 147);
    public static SvgColor DeepSkyBlue { get; } = new(0, 191, 255);
    public static SvgColor DimGray { get; } = new(105, 105, 105);
    public static SvgColor DimGrey { get; } = new(105, 105, 105);
    public static SvgColor DodgerBlue { get; } = new(30, 144, 255);
    public static SvgColor Firebrick { get; } = new(178, 34, 34);
    public static SvgColor FloralWhite { get; } = new(255, 250, 240);
    public static SvgColor ForestGreen { get; } = new(34, 139, 34);
    public static SvgColor Fuchsia { get; } = new(255, 0, 255);
    public static SvgColor Gainsboro { get; } = new(220, 220, 220);
    public static SvgColor GhostWhite { get; } = new(248, 248, 255);
    public static SvgColor Gold { get; } = new(255, 215, 0);
    public static SvgColor Goldenrod { get; } = new(218, 165, 32);
    public static SvgColor Gray { get; } = new(128, 128, 128);
    public static SvgColor Green { get; } = new(0, 128, 0);
    public static SvgColor GreenYellow { get; } = new(173, 255, 47);
    public static SvgColor Grey { get; } = new(128, 128, 128);
    public static SvgColor Honeydew { get; } = new(240, 255, 240);
    public static SvgColor HotPink { get; } = new(255, 105, 180);
    public static SvgColor IndianRed { get; } = new(205, 92, 92);
    public static SvgColor Indigo { get; } = new(75, 0, 130);
    public static SvgColor Ivory { get; } = new(255, 255, 240);
    public static SvgColor Khaki { get; } = new(240, 230, 140);
    public static SvgColor Lavender { get; } = new(230, 230, 250);
    public static SvgColor LavenderBlush { get; } = new(255, 240, 245);
    public static SvgColor LawnGreen { get; } = new(124, 252, 0);
    public static SvgColor LemonChiffon { get; } = new(255, 250, 205);
    public static SvgColor LightBlue { get; } = new(173, 216, 230);
    public static SvgColor LightCoral { get; } = new(240, 128, 128);
    public static SvgColor LightCyan { get; } = new(224, 255, 255);
    public static SvgColor LightGoldenrodYellow { get; } = new(250, 250, 210);
    public static SvgColor LightGray { get; } = new(211, 211, 211);
    public static SvgColor LightGreen { get; } = new(144, 238, 144);
    public static SvgColor LightGrey { get; } = new(211, 211, 211);
    public static SvgColor LightPink { get; } = new(255, 182, 193);
    public static SvgColor LightSalmon { get; } = new(255, 160, 122);
    public static SvgColor LightSeaGreen { get; } = new(32, 178, 170);
    public static SvgColor LightSkyBlue { get; } = new(135, 206, 250);
    public static SvgColor LightSlateGray { get; } = new(119, 136, 153);
    public static SvgColor LightSlateGrey { get; } = new(119, 136, 153);
    public static SvgColor LightSteelBlue { get; } = new(176, 196, 222);
    public static SvgColor LightYellow { get; } = new(255, 255, 224);
    public static SvgColor Lime { get; } = new(0, 255, 0);
    public static SvgColor LimeGreen { get; } = new(50, 205, 50);
    public static SvgColor Linen { get; } = new(250, 240, 230);
    public static SvgColor Magenta { get; } = new(255, 0, 255);
    public static SvgColor Maroon { get; } = new(128, 0, 0);
    public static SvgColor MediumAquamarine { get; } = new(102, 205, 170);
    public static SvgColor MediumBlue { get; } = new(0, 0, 205);
    public static SvgColor MediumOrchid { get; } = new(186, 85, 211);
    public static SvgColor MediumPurple { get; } = new(147, 112, 219);
    public static SvgColor MediumSeaGreen { get; } = new(60, 179, 113);
    public static SvgColor MediumSlateBlue { get; } = new(123, 104, 238);
    public static SvgColor MediumSpringGreen { get; } = new(0, 250, 154);
    public static SvgColor MediumTurquoise { get; } = new(72, 209, 204);
    public static SvgColor MediumVioletRed { get; } = new(199, 21, 133);
    public static SvgColor MidnightBlue { get; } = new(25, 25, 112);
    public static SvgColor MintCream { get; } = new(245, 255, 250);
    public static SvgColor MistyRose { get; } = new(255, 228, 225);
    public static SvgColor Moccasin { get; } = new(255, 228, 181);
    public static SvgColor NavajoWhite { get; } = new(255, 222, 173);
    public static SvgColor Navy { get; } = new(0, 0, 128);
    public static SvgColor OldLace { get; } = new(253, 245, 230);
    public static SvgColor Olive { get; } = new(128, 128, 0);
    public static SvgColor OliveDrab { get; } = new(107, 142, 35);
    public static SvgColor Orange { get; } = new(255, 165, 0);
    public static SvgColor OrangeRed { get; } = new(255, 69, 0);
    public static SvgColor Orchid { get; } = new(218, 112, 214);
    public static SvgColor PaleGoldenRod { get; } = new(238, 232, 170);
    public static SvgColor PaleGreen { get; } = new(152, 251, 152);
    public static SvgColor PaleTurquoise { get; } = new(175, 238, 238);
    public static SvgColor PaleVioletRed { get; } = new(219, 112, 147);
    public static SvgColor PapayaWhip { get; } = new(255, 239, 213);
    public static SvgColor PeachPuff { get; } = new(255, 218, 185);
    public static SvgColor Peru { get; } = new(205, 133, 63);
    public static SvgColor Pink { get; } = new(255, 192, 203);
    public static SvgColor Plum { get; } = new(221, 160, 221);
    public static SvgColor PowderBlue { get; } = new(176, 224, 230);
    public static SvgColor Purple { get; } = new(128, 0, 128);
    public static SvgColor RebeccaPurple { get; } = new(102, 51, 153);
    public static SvgColor Red { get; } = new(255, 0, 0);
    public static SvgColor RosyBrown { get; } = new(188, 143, 143);
    public static SvgColor RoyalBlue { get; } = new(65, 105, 225);
    public static SvgColor SaddleBrown { get; } = new(139, 69, 19);
    public static SvgColor Salmon { get; } = new(250, 128, 114);
    public static SvgColor SandyBrown { get; } = new(244, 164, 96);
    public static SvgColor SeaGreen { get; } = new(46, 139, 87);
    public static SvgColor Seashell { get; } = new(255, 245, 238);
    public static SvgColor Sienna { get; } = new(160, 82, 45);
    public static SvgColor Silver { get; } = new(192, 192, 192);
    public static SvgColor SkyBlue { get; } = new(135, 206, 235);
    public static SvgColor SlateBlue { get; } = new(106, 90, 205);
    public static SvgColor SlateGray { get; } = new(112, 128, 144);
    public static SvgColor SlateGrey { get; } = new(112, 128, 144);
    public static SvgColor Snow { get; } = new(255, 250, 250);
    public static SvgColor SpringGreen { get; } = new(0, 255, 127);
    public static SvgColor SteelBlue { get; } = new(70, 130, 180);
    public static SvgColor Tan { get; } = new(210, 180, 140);
    public static SvgColor Teal { get; } = new(0, 128, 128);
    public static SvgColor Thistle { get; } = new(216, 191, 216);
    public static SvgColor Tomato { get; } = new(255, 99, 71);
    public static SvgColor Turquoise { get; } = new(64, 224, 208);
    public static SvgColor Violet { get; } = new(238, 130, 238);
    public static SvgColor Wheat { get; } = new(245, 222, 179);
    public static SvgColor White { get; } = new(255, 255, 255);
    public static SvgColor WhiteSmoke { get; } = new(245, 245, 245);
    public static SvgColor Yellow { get; } = new(255, 255, 0);
    public static SvgColor YellowGreen { get; } = new(154, 205, 50);

    public static SvgColor Get(string name)
    {
        return name.Trim().ToLower() switch
        {
            "aliceblue" => AliceBlue,
            "antiquewhite" => AntiqueWhite,
            "aqua" => Aqua,
            "aquamarine" => Aquamarine,
            "azure" => Azure,
            "beige" => Beige,
            "bisque" => Bisque,
            "black" => Black,
            "blanchedalmond" => BlanchedAlmond,
            "blue" => Blue,
            "blueviolet" => BlueViolet,
            "brown" => Brown,
            "burlywood" => BurlyWood,
            "cadetblue" => CadetBlue,
            "chartreuse" => Chartreuse,
            "chocolate" => Chocolate,
            "coral" => Coral,
            "cornflowerblue" => CornFlowerBlue,
            "cornsilk" => CornSilk,
            "crimson" => Crimson,
            "cyan" => Cyan,
            "darkblue" => DarkBlue,
            "darkcyan" => DarkCyan,
            "darkgoldenrod" => DarkGoldenRod,
            "darkgray" => DarkGray,
            "darkgreen" => DarkGreen,
            "darkgrey" => DarkGrey,
            "darkkhaki" => DarkKhaki,
            "darkmagenta" => DarkMagenta,
            "darkolivegreen" => DarkOliveGreen,
            "darkorange" => DarkOrange,
            "darkorchid" => DarkOrchid,
            "darkred" => DarkRed,
            "darksalmon" => DarkSalmon,
            "darkseagreen" => DarkSeaGreen,
            "darkslateblue" => DarkSlateBlue,
            "darkslategray" => DarkSlateGray,
            "darkslategrey" => DarkSlateGrey,
            "darkturquoise" => DarkTurquoise,
            "darkviolet" => DarkViolet,
            "deeppink" => DeepPink,
            "deepskyblue" => DeepSkyBlue,
            "dimgray" => DimGray,
            "dimgrey" => DimGrey,
            "dodgerblue" => DodgerBlue,
            "firebrick" => Firebrick,
            "floralwhite" => FloralWhite,
            "forestgreen" => ForestGreen,
            "fuchsia" => Fuchsia,
            "gainsboro" => Gainsboro,
            "ghostwhite" => GhostWhite,
            "gold" => Gold,
            "goldenrod" => Goldenrod,
            "gray" => Gray,
            "green" => Green,
            "greenyellow" => GreenYellow,
            "grey" => Grey,
            "honeydew" => Honeydew,
            "hotpink" => HotPink,
            "indianred" => IndianRed,
            "indigo" => Indigo,
            "ivory" => Ivory,
            "khaki" => Khaki,
            "lavender" => Lavender,
            "lavenderblush" => LavenderBlush,
            "lawngreen" => LawnGreen,
            "lemonchiffon" => LemonChiffon,
            "lightblue" => LightBlue,
            "lightcoral" => LightCoral,
            "lightcyan" => LightCyan,
            "lightgoldenrodyellow" => LightGoldenrodYellow,
            "lightgray" => LightGray,
            "lightgreen" => LightGreen,
            "lightgrey" => LightGrey,
            "lightpink" => LightPink,
            "lightsalmon" => LightSalmon,
            "lightseagreen" => LightSeaGreen,
            "lightskyblue" => LightSkyBlue,
            "lightslategray" => LightSlateGray,
            "lightslategrey" => LightSlateGrey,
            "lightsteelblue" => LightSteelBlue,
            "lightyellow" => LightYellow,
            "lime" => Lime,
            "limegreen" => LimeGreen,
            "linen" => Linen,
            "magenta" => Magenta,
            "maroon" => Maroon,
            "mediumaquamarine" => MediumAquamarine,
            "mediumblue" => MediumBlue,
            "mediumorchid" => MediumOrchid,
            "mediumpurple" => MediumPurple,
            "mediumseagreen" => MediumSeaGreen,
            "mediumslateblue" => MediumSlateBlue,
            "mediumspringgreen" => MediumSpringGreen,
            "mediumturquoise" => MediumTurquoise,
            "mediumvioletred" => MediumVioletRed,
            "midnightblue" => MidnightBlue,
            "mintcream" => MintCream,
            "mistyrose" => MistyRose,
            "moccasin" => Moccasin,
            "navajowhite" => NavajoWhite,
            "navy" => Navy,
            "oldlace" => OldLace,
            "olive" => Olive,
            "olivedrab" => OliveDrab,
            "orange" => Orange,
            "orangered" => OrangeRed,
            "orchid" => Orchid,
            "palegoldenrod" => PaleGoldenRod,
            "palegreen" => PaleGreen,
            "paleturquoise" => PaleTurquoise,
            "palevioletred" => PaleVioletRed,
            "papayawhip" => PapayaWhip,
            "peachpuff" => PeachPuff,
            "peru" => Peru,
            "pink" => Pink,
            "plum" => Plum,
            "powderblue" => PowderBlue,
            "purple" => Purple,
            "rebeccapurple" => RebeccaPurple,
            "red" => Red,
            "rosybrown" => RosyBrown,
            "royalblue" => RoyalBlue,
            "saddlebrown" => SaddleBrown,
            "salmon" => Salmon,
            "sandybrown" => SandyBrown,
            "seagreen" => SeaGreen,
            "seashell" => Seashell,
            "sienna" => Sienna,
            "silver" => Silver,
            "skyblue" => SkyBlue,
            "slateblue" => SlateBlue,
            "slategray" => SlateGray,
            "slategrey" => SlateGrey,
            "snow" => Snow,
            "springgreen" => SpringGreen,
            "steelblue" => SteelBlue,
            "tan" => Tan,
            "teal" => Teal,
            "thistle" => Thistle,
            "tomato" => Tomato,
            "turquoise" => Turquoise,
            "violet" => Violet,
            "wheat" => Wheat,
            "white" => White,
            "whitesmoke" => WhiteSmoke,
            "yellow" => Yellow,
            "yellowgreen" => YellowGreen,
            _ => null
        };
    }
}