// SvgToXaml
// Copyright (C) 2022-2024 Dust in the Wind
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace DustInTheWind.SvgToXaml.Svg;

internal static class SvgNamedColors
{
    public static SvgColor AliceBlue { get; } = new(240, 248, 255);
    public static SvgColor AntiqueWhite { get; } = new(250, 235, 215);
    public static SvgColor Aqua { get; } = new(0, 255, 255);
    public static SvgColor Aquamarine { get; } = new(127, 255, 212);
    public static SvgColor Azure { get; } = new(240, 255, 255);
    public static SvgColor Beige { get; } = new(245, 245, 220);
    public static SvgColor Bisque { get; } = new(255, 228, 196);
    public static SvgColor Black { get; } = new(0, 0, 0);
    public static SvgColor BlanchedAlmond { get; } = new(255, 235, 205);
    public static SvgColor Blue { get; } = new(0, 0, 255);
    public static SvgColor BlueViolet { get; } = new(138, 43, 226);
    public static SvgColor Brown { get; } = new(165, 42, 42);
    public static SvgColor BurlyWood { get; } = new(222, 184, 135);
    public static SvgColor CadetBlue { get; } = new(95, 158, 160);
    public static SvgColor Chartreuse { get; } = new(127, 255, 0);
    public static SvgColor Chocolate { get; } = new(210, 105, 30);
    public static SvgColor Coral { get; } = new(255, 127, 80);
    public static SvgColor CornFlowerBlue { get; } = new(100, 149, 237);
    public static SvgColor CornSilk { get; } = new(255, 248, 220);
    public static SvgColor Crimson { get; } = new(220, 20, 60);
    public static SvgColor Cyan { get; } = new(0, 255, 255);
    public static SvgColor DarkBlue { get; } = new(0, 0, 139);
    public static SvgColor DarkCyan { get; } = new(0, 139, 139);
    public static SvgColor DarkGoldenRod { get; } = new(184, 134, 11);
    public static SvgColor DarkGray { get; } = new(169, 169, 169);
    public static SvgColor Darkgreen { get; } = new(0, 100, 0);
    public static SvgColor Darkgrey { get; } = new(169, 169, 169);
    public static SvgColor Darkkhaki { get; } = new(189, 183, 107);
    public static SvgColor Darkmagenta { get; } = new(139, 0, 139);
    public static SvgColor Darkolivegreen { get; } = new(85, 107, 47);
    public static SvgColor Darkorange { get; } = new(255, 140, 0);
    public static SvgColor Darkorchid { get; } = new(153, 50, 204);
    public static SvgColor Darkred { get; } = new(139, 0, 0);
    public static SvgColor Darksalmon { get; } = new(233, 150, 122);
    public static SvgColor Darkseagreen { get; } = new(143, 188, 143);
    public static SvgColor Darkslateblue { get; } = new(72, 61, 139);
    public static SvgColor Darkslategray { get; } = new(47, 79, 79);
    public static SvgColor Darkslategrey { get; } = new(47, 79, 79);
    public static SvgColor Darkturquoise { get; } = new(0, 206, 209);
    public static SvgColor Darkviolet { get; } = new(148, 0, 211);
    public static SvgColor Deeppink { get; } = new(255, 20, 147);
    public static SvgColor Deepskyblue { get; } = new(0, 191, 255);
    public static SvgColor Dimgray { get; } = new(105, 105, 105);
    public static SvgColor Dimgrey { get; } = new(105, 105, 105);
    public static SvgColor Dodgerblue { get; } = new(30, 144, 255);
    public static SvgColor Firebrick { get; } = new(178, 34, 34);
    public static SvgColor Floralwhite { get; } = new(255, 250, 240);
    public static SvgColor Forestgreen { get; } = new(34, 139, 34);
    public static SvgColor Fuchsia { get; } = new(255, 0, 255);
    public static SvgColor Gainsboro { get; } = new(220, 220, 220);
    public static SvgColor Ghostwhite { get; } = new(248, 248, 255);
    public static SvgColor Gold { get; } = new(255, 215, 0);
    public static SvgColor Goldenrod { get; } = new(218, 165, 32);
    public static SvgColor Gray { get; } = new(128, 128, 128);
    public static SvgColor Green { get; } = new(0, 128, 0);
    public static SvgColor Greenyellow { get; } = new(173, 255, 47);
    public static SvgColor Grey { get; } = new(128, 128, 128);
    public static SvgColor Honeydew { get; } = new(240, 255, 240);
    public static SvgColor Hotpink { get; } = new(255, 105, 180);
    public static SvgColor Indianred { get; } = new(205, 92, 92);
    public static SvgColor Indigo { get; } = new(75, 0, 130);
    public static SvgColor Ivory { get; } = new(255, 255, 240);
    public static SvgColor Khaki { get; } = new(240, 230, 140);
    public static SvgColor Lavender { get; } = new(230, 230, 250);
    public static SvgColor Lavenderblush { get; } = new(255, 240, 245);
    public static SvgColor Lawngreen { get; } = new(124, 252, 0);
    public static SvgColor Lemonchiffon { get; } = new(255, 250, 205);
    public static SvgColor Lightblue { get; } = new(173, 216, 230);
    public static SvgColor Lightcoral { get; } = new(240, 128, 128);
    public static SvgColor Lightcyan { get; } = new(224, 255, 255);
    public static SvgColor Lightgoldenrodyellow { get; } = new(250, 250, 210);
    public static SvgColor Lightgray { get; } = new(211, 211, 211);
    public static SvgColor Lightgreen { get; } = new(144, 238, 144);
    public static SvgColor Lightgrey { get; } = new(211, 211, 211);
    public static SvgColor Lightpink { get; } = new(255, 182, 193);
    public static SvgColor Lightsalmon { get; } = new(255, 160, 122);
    public static SvgColor Lightseagreen { get; } = new(32, 178, 170);
    public static SvgColor Lightskyblue { get; } = new(135, 206, 250);
    public static SvgColor Lightslategray { get; } = new(119, 136, 153);
    public static SvgColor Lightslategrey { get; } = new(119, 136, 153);
    public static SvgColor Lightsteelblue { get; } = new(176, 196, 222);
    public static SvgColor Lightyellow { get; } = new(255, 255, 224);
    public static SvgColor Lime { get; } = new(0, 255, 0);
    public static SvgColor Limegreen { get; } = new(50, 205, 50);
    public static SvgColor Linen { get; } = new(250, 240, 230);
    public static SvgColor Magenta { get; } = new(255, 0, 255);
    public static SvgColor Maroon { get; } = new(128, 0, 0);
    public static SvgColor Mediumaquamarine { get; } = new(102, 205, 170);
    public static SvgColor Mediumblue { get; } = new(0, 0, 205);
    public static SvgColor Mediumorchid { get; } = new(186, 85, 211);
    public static SvgColor Mediumpurple { get; } = new(147, 112, 219);
    public static SvgColor Mediumseagreen { get; } = new(60, 179, 113);
    public static SvgColor Mediumslateblue { get; } = new(123, 104, 238);
    public static SvgColor Mediumspringgreen { get; } = new(0, 250, 154);
    public static SvgColor Mediumturquoise { get; } = new(72, 209, 204);
    public static SvgColor Mediumvioletred { get; } = new(199, 21, 133);
    public static SvgColor Midnightblue { get; } = new(25, 25, 112);
    public static SvgColor Mintcream { get; } = new(245, 255, 250);
    public static SvgColor Mistyrose { get; } = new(255, 228, 225);
    public static SvgColor Moccasin { get; } = new(255, 228, 181);
    public static SvgColor Navajowhite { get; } = new(255, 222, 173);
    public static SvgColor Navy { get; } = new(0, 0, 128);
    public static SvgColor Oldlace { get; } = new(253, 245, 230);
    public static SvgColor Olive { get; } = new(128, 128, 0);
    public static SvgColor Olivedrab { get; } = new(107, 142, 35);
    public static SvgColor Orange { get; } = new(255, 165, 0);
    public static SvgColor Orangered { get; } = new(255, 69, 0);
    public static SvgColor Orchid { get; } = new(218, 112, 214);
    public static SvgColor Palegoldenrod { get; } = new(238, 232, 170);
    public static SvgColor Palegreen { get; } = new(152, 251, 152);
    public static SvgColor Paleturquoise { get; } = new(175, 238, 238);
    public static SvgColor Palevioletred { get; } = new(219, 112, 147);
    public static SvgColor Papayawhip { get; } = new(255, 239, 213);
    public static SvgColor Peachpuff { get; } = new(255, 218, 185);
    public static SvgColor Peru { get; } = new(205, 133, 63);
    public static SvgColor Pink { get; } = new(255, 192, 203);
    public static SvgColor Plum { get; } = new(221, 160, 221);
    public static SvgColor Powderblue { get; } = new(176, 224, 230);
    public static SvgColor Purple { get; } = new(128, 0, 128);
    public static SvgColor Rebeccapurple { get; } = new(102, 51, 153);
    public static SvgColor Red { get; } = new(255, 0, 0);
    public static SvgColor Rosybrown { get; } = new(188, 143, 143);
    public static SvgColor Royalblue { get; } = new(65, 105, 225);
    public static SvgColor Saddlebrown { get; } = new(139, 69, 19);
    public static SvgColor Salmon { get; } = new(250, 128, 114);
    public static SvgColor Sandybrown { get; } = new(244, 164, 96);
    public static SvgColor Seagreen { get; } = new(46, 139, 87);
    public static SvgColor Seashell { get; } = new(255, 245, 238);
    public static SvgColor Sienna { get; } = new(160, 82, 45);
    public static SvgColor Silver { get; } = new(192, 192, 192);
    public static SvgColor Skyblue { get; } = new(135, 206, 235);
    public static SvgColor Slateblue { get; } = new(106, 90, 205);
    public static SvgColor Slategray { get; } = new(112, 128, 144);
    public static SvgColor Slategrey { get; } = new(112, 128, 144);
    public static SvgColor Snow { get; } = new(255, 250, 250);
    public static SvgColor Springgreen { get; } = new(0, 255, 127);
    public static SvgColor Steelblue { get; } = new(70, 130, 180);
    public static SvgColor Tan { get; } = new(210, 180, 140);
    public static SvgColor Teal { get; } = new(0, 128, 128);
    public static SvgColor Thistle { get; } = new(216, 191, 216);
    public static SvgColor Tomato { get; } = new(255, 99, 71);
    public static SvgColor Turquoise { get; } = new(64, 224, 208);
    public static SvgColor Violet { get; } = new(238, 130, 238);
    public static SvgColor Wheat { get; } = new(245, 222, 179);
    public static SvgColor White { get; } = new(255, 255, 255);
    public static SvgColor Whitesmoke { get; } = new(245, 245, 245);
    public static SvgColor Yellow { get; } = new(255, 255, 0);
    public static SvgColor Yellowgreen { get; } = new(154, 205, 50);

    public static SvgColor Get(string name)
    {
        return name.Trim().ToLower() switch
        {
            "aliceblue" => AliceBlue,
            "antiquewhite" => AntiqueWhite,
            "aqua" => Aqua,
            "aquamarine" => Aquamarine,
            "azure" => Azure,
            "beige" => Beige,
            "bisque" => Bisque,
            "black" => Black,
            "blanchedalmond" => BlanchedAlmond,
            "blue" => Blue,
            "blueviolet" => BlueViolet,
            "brown" => Brown,
            "burlywood" => BurlyWood,
            "cadetblue" => CadetBlue,
            "chartreuse" => Chartreuse,
            "chocolate" => Chocolate,
            "coral" => Coral,
            "cornflowerblue" => CornFlowerBlue,
            "cornsilk" => CornSilk,
            "crimson" => Crimson,
            "cyan" => Cyan,
            "darkblue" => DarkBlue,
            "darkcyan" => DarkCyan,
            "darkgoldenrod" => DarkGoldenRod,
            "darkgray" => DarkGray,
            "darkgreen" => Darkgreen,
            "darkgrey" => Darkgrey,
            "darkkhaki" => Darkkhaki,
            "darkmagenta" => Darkmagenta,
            "darkolivegreen" => Darkolivegreen,
            "darkorange" => Darkorange,
            "darkorchid" => Darkorchid,
            "darkred" => Darkred,
            "darksalmon" => Darksalmon,
            "darkseagreen" => Darkseagreen,
            "darkslateblue" => Darkslateblue,
            "darkslategray" => Darkslategray,
            "darkslategrey" => Darkslategrey,
            "darkturquoise" => Darkturquoise,
            "darkviolet" => Darkviolet,
            "deeppink" => Deeppink,
            "deepskyblue" => Deepskyblue,
            "dimgray" => Dimgray,
            "dimgrey" => Dimgrey,
            "dodgerblue" => Dodgerblue,
            "firebrick" => Firebrick,
            "floralwhite" => Floralwhite,
            "forestgreen" => Forestgreen,
            "fuchsia" => Fuchsia,
            "gainsboro" => Gainsboro,
            "ghostwhite" => Ghostwhite,
            "gold" => Gold,
            "goldenrod" => Goldenrod,
            "gray" => Gray,
            "green" => Green,
            "greenyellow" => Greenyellow,
            "grey" => Grey,
            "honeydew" => Honeydew,
            "hotpink" => Hotpink,
            "indianred" => Indianred,
            "indigo" => Indigo,
            "ivory" => Ivory,
            "khaki" => Khaki,
            "lavender" => Lavender,
            "lavenderblush" => Lavenderblush,
            "lawngreen" => Lawngreen,
            "lemonchiffon" => Lemonchiffon,
            "lightblue" => Lightblue,
            "lightcoral" => Lightcoral,
            "lightcyan" => Lightcyan,
            "lightgoldenrodyellow" => Lightgoldenrodyellow,
            "lightgray" => Lightgray,
            "lightgreen" => Lightgreen,
            "lightgrey" => Lightgrey,
            "lightpink" => Lightpink,
            "lightsalmon" => Lightsalmon,
            "lightseagreen" => Lightseagreen,
            "lightskyblue" => Lightskyblue,
            "lightslategray" => Lightslategray,
            "lightslategrey" => Lightslategrey,
            "lightsteelblue" => Lightsteelblue,
            "lightyellow" => Lightyellow,
            "lime" => Lime,
            "limegreen" => Limegreen,
            "linen" => Linen,
            "magenta" => Magenta,
            "maroon" => Maroon,
            "mediumaquamarine" => Mediumaquamarine,
            "mediumblue" => Mediumblue,
            "mediumorchid" => Mediumorchid,
            "mediumpurple" => Mediumpurple,
            "mediumseagreen" => Mediumseagreen,
            "mediumslateblue" => Mediumslateblue,
            "mediumspringgreen" => Mediumspringgreen,
            "mediumturquoise" => Mediumturquoise,
            "mediumvioletred" => Mediumvioletred,
            "midnightblue" => Midnightblue,
            "mintcream" => Mintcream,
            "mistyrose" => Mistyrose,
            "moccasin" => Moccasin,
            "navajowhite" => Navajowhite,
            "navy" => Navy,
            "oldlace" => Oldlace,
            "olive" => Olive,
            "olivedrab" => Olivedrab,
            "orange" => Orange,
            "orangered" => Orangered,
            "orchid" => Orchid,
            "palegoldenrod" => Palegoldenrod,
            "palegreen" => Palegreen,
            "paleturquoise" => Paleturquoise,
            "palevioletred" => Palevioletred,
            "papayawhip" => Papayawhip,
            "peachpuff" => Peachpuff,
            "peru" => Peru,
            "pink" => Pink,
            "plum" => Plum,
            "powderblue" => Powderblue,
            "purple" => Purple,
            "rebeccapurple" => Rebeccapurple,
            "red" => Red,
            "rosybrown" => Rosybrown,
            "royalblue" => Royalblue,
            "saddlebrown" => Saddlebrown,
            "salmon" => Salmon,
            "sandybrown" => Sandybrown,
            "seagreen" => Seagreen,
            "seashell" => Seashell,
            "sienna" => Sienna,
            "silver" => Silver,
            "skyblue" => Skyblue,
            "slateblue" => Slateblue,
            "slategray" => Slategray,
            "slategrey" => Slategrey,
            "snow" => Snow,
            "springgreen" => Springgreen,
            "steelblue" => Steelblue,
            "tan" => Tan,
            "teal" => Teal,
            "thistle" => Thistle,
            "tomato" => Tomato,
            "turquoise" => Turquoise,
            "violet" => Violet,
            "wheat" => Wheat,
            "white" => White,
            "whitesmoke" => Whitesmoke,
            "yellow" => Yellow,
            "yellowgreen" => Yellowgreen,
            _ => null
        };
    }
}